### ISSUE TITLE
Implementation concerns.

### ISSUE THREAD

**Issue by rvlander** [ROBERT-proximity-tracing/documents#51]
I am afraid StopCovid is going to cost loads of money for nothing.
The list of involved companies is massive:
* Inria: coordination and transmission protocol, privacy-by-design;
* ANSSI: cybersecurity;
* Capgemini: back-end architecture and development;
* Dassault Systèmes: SecNumCloud qualified sovereign data infrastructure;
* Inserm: health models;
* Lunabee Studio: development of mobile applications;
* Orange: application distribution and interoperability;
* Santé Publique France: integration and coordination of the application in the global strategy of contact tracing;
* Withings: connected objects.

They have 13 days left. How can it even be ready. How the government chose these companies? Why not use smaller companies that are desperately need money and know how to deal with uncertainty and short deadlines? By using huge companies, communication between all these entities is gonna kill the thing and make it obsolete.

To my government: we are not building a new Airplane and do not need to to make every big companies happy with a piece of the cake (and a bag of coins). People are dying.

To INRIA: all concerns that people took time to explains here are unanswered. Why make this public then? Why INRIA was seen as the best entity to make the protocol knowing that their are tons of security laboratory in France with talented people?

Anyway all of this, as a Frenchman, makes me sick.

**Comment by claustres** [comment]
Your comment should probably be associated with this issue https://github.com/ROBERT-proximity-tracing/documents/issues/40 to avoid duplicates.

**Comment by beng-git** [comment]
Although I think this issue is offtopic, I'd like to point out that as it is stated in https://www.inria.fr/fr/stopcovid :

"Le projet, dans sa phase de construction d’un prototype, implique des organisations publiques et privées **agissant à titre gracieux**, au sein de l’équipe-projet StopCovid."

Would "smaller companies that are desperately need money" want to work for free ? 

Furthermore, the list of participants in the project lists both very large companies and much smaller companies.

**Comment by claustres** [comment]
First I would like to highlight that public institutions working for free is an oxymoron. Maybe I am wrong and I would like to have feedback about that but according to their status in France I don't think the involved researchers will stop being paid by the state during their journey on the project. They simply changed their focus from their previous research interests to this new one. Maybe they are working more than usual to tackle this issue, I don't have any doubt about that, but this is definitely not "for free".

About private actors, maybe they are working "for free" during the prototype phase but I think they can expect a lot of return, notably for their image and in the production phase. First, this is an incredibly powerful advertisement, I think a lot of small companies would be happy to work "for free" for such a publicity. Then, as they have participated to the system design, they will naturally be in good position to handle the run of the production system, and we don't have any guarantee that they will continue working for free during this phase. Last but not least, some of the large companies involved today are putting part-time work in place, eg [capgemini](https://blogs.mediapart.fr/robert-amade/blog/180420/covid-capgemini-aux-actionnaires-de-faire-des-efforts) - [sopra](https://www.gestionsociale.fr/effet-daubaine-chomage-partiel-retroactif-chez-sopra-steria/), because some of their salaries cannot work for their usual customers. So making them available for such a project can also be partly viewed as an investment, not really without expecting any return.

Don't get me wrong, I am not sure of all of this but I am questioning myself, and the fact that the communication around this project is not really transparent does not help.

**Comment by claustres** [comment]
Maybe you will find some insight about some of their "motivations" now https://www.20minutes.fr/societe/2797463-20200611-stopcovid-anticor-alerte-parquet-soupcons-favoritisme

**Comment by rvlander** [comment]
Business as usual...
